In [5]:
import pandas as pd
import numpy as np
from matplotlib import dates
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import tqdm

In [6]:
df_all = pd.read_csv(r'data/total_dataset_A.csv', low_memory=False)
df_all['Time'] = pd.to_datetime(df_all['Time'])

In [7]:
print('기존데이터 갯수 :' , len(df_all))

기존데이터 갯수 : 10154368

## all racks data fill

In [8]:
def fill_data(df, start_time: str, end_time: str):
    start = pd.Timestamp(start_time)
    end   = pd.Timestamp(end_time)
    target = ['Time', 'Tmp', 'TmpMax', 'TmpMin', 'VCell', 'VCellMax', 'VCellMin', 'AChaMax', 'ADisChaMax', 'SoC']

    for i in range(14):
        temp_df = df[(start <= df['Time']) & (df['Time'] <= end) & (df['Racks'] == f'racks_{i}')].loc[:, target]
        temp_df = temp_df.replace(np.float64(0.0), np.NAN)
        for e in temp_df.columns[1:]:
            temp_df[e] = pd.Series(temp_df[e]).interpolate()
        df.loc[temp_df.index[0]:temp_df.index[-1], target] = temp_df
    return df

In [9]:
df_all = fill_data(df=df_all, start_time='2019-01-18 00:00:00', end_time='2019-01-18 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-01-28 00:00:00', end_time='2019-01-28 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-03-20 00:00:00', end_time='2019-03-20 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-04-11 00:00:00', end_time='2019-04-11 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-04-12 00:00:00', end_time='2019-04-12 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-04-13 00:00:00', end_time='2019-04-13 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-04-25 00:00:00', end_time='2019-04-25 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-05-20 00:00:00', end_time='2019-05-20 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-06-05 00:00:00', end_time='2019-06-05 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-06-07 00:00:00', end_time='2019-06-07 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-06-29 00:00:00', end_time='2019-06-29 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-07-03 00:00:00', end_time='2019-07-03 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-07-22 00:00:00', end_time='2019-07-22 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-07-28 00:00:00', end_time='2019-07-28 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-08-13 00:00:00', end_time='2019-08-13 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-08-31 00:00:00', end_time='2019-08-31 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-09-03 00:00:00', end_time='2019-09-03 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-09-10 00:00:00', end_time='2019-09-10 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-09-19 00:00:00', end_time='2019-09-19 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-10-14 00:00:00', end_time='2019-10-14 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-10-15 00:00:00', end_time='2019-10-15 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-10-16 00:00:00', end_time='2019-10-16 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-10-19 00:00:00', end_time='2019-10-19 23:59:00')
df_all = fill_data(df=df_all, start_time='2019-10-22 00:00:00', end_time='2019-10-22 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-11-13 00:00:00', end_time='2019-11-13 23:59:00')

df_all = fill_data(df=df_all, start_time='2019-12-26 00:00:00', end_time='2019-12-26 23:59:00')

df_all = fill_data(df=df_all, start_time='2020-01-03 00:00:00', end_time='2020-01-03 23:59:00')

df_all = fill_data(df=df_all, start_time='2020-04-06 00:00:00', end_time='2020-04-06 23:59:00')

## data drop

In [10]:
def drop_data(df, start_time: str, end_time: str, target_rack: str):
    start = pd.Timestamp(start_time)
    end   = pd.Timestamp(end_time)
    target = ['Time', 'Tmp', 'TmpMax', 'TmpMin', 'VCell', 'VCellMax', 'VCellMin', 'AChaMax', 'ADisChaMax', 'SoC']

    temp_df = df[(start <= df['Time']) & (df['Time'] <= end) & (df['Racks'] == f'{target_rack}')].loc[:, target]
    print(len(temp_df))
    df = df.drop(index=temp_df.index)
    return df

In [11]:
df_all = drop_data(df_all, "2019-09-03 00:00:00", "2019-09-03 23:59:00", "racks_1")
df_all = drop_data(df_all, "2019-09-03 00:00:00", "2019-09-03 23:59:00", "racks_12")

1438
1438

In [12]:
print("새로운데이터셋 갯수 :",len(df_all))

새로운데이터셋 갯수 : 10151492

In [17]:
df_all

,Time,Tmp,TmpMax,TmpMin,VCell,VCellMax,VCellMin,A,AChaMax,ADisChaMax,EvtVnd1,EvtVnd2,EvtVnd3,SoC,V,W,WChaMax,WDisChaMax,Racks
0,2019-01-01 00:00:00,23.5,25.5,21.5,3.429,3.452,3.402,0.0,149.2,95.1,NaN,NaN,NaN,4.0,816.3,0.0,121800.0,77700.0,racks_0
1,2019-01-01 00:01:00,23.5,25.5,21.5,3.429,3.452,3.402,0.0,149.2,95.1,NaN,NaN,NaN,4.0,816.3,0.0,121800.0,77700.0,racks_0
2,2019-01-01 00:02:00,23.5,25.5,21.5,3.429,3.452,3.401,0.0,149.2,95.1,NaN,NaN,NaN,4.0,816.3,0.0,121800.0,77700.0,racks_0
3,2019-01-01 00:03:00,23.5,25.5,21.5,3.429,3.452,3.401,0.0,149.2,95.1,NaN,NaN,NaN,4.0,816.3,0.0,121800.0,77700.0,racks_0
4,2019-01-01 00:04:00,23.5,25.5,21.5,3.429,3.454,3.402,0.0,149.2,95.1,NaN,NaN,NaN,4.0,816.3,0.0,121800.0,77700.0,racks_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10154363,2020-07-11 17:51:00,25.0,25.0,24.5,3.852,3.858,3.841,0.0,132.8,132.8,NaN,NaN,NaN,70.5,916.7,0.0,121800.0,121800.0,racks_13
10154364,2020-07-11 17:52:00,25.0,25.0,24.5,3.852,3.858,3.841,0.0,132.8,132.8,NaN,NaN,NaN,70.5,916.7,0.0,121800.0,121800.0,racks_13
10154365,2020-07-11 17:53:00,25.0,25.0,24.5,3.852,3.858,3.841,0.0,132.8,132.8,NaN,NaN,NaN,70.5,916.7,0.0,121800.0,121800.0,racks_13
10154366,2020-07-11 17:54:00,25.0,25.0,24.5,3.851,3.859,3.841,0.0,132.8,132.8,NaN,NaN,NaN,70.5,916.7,0.0,121800.0,121800.0,racks_13
10154367,2020-07-11 17:55:00,25.0,25.0,24.5,3.851,3.859,3.841,0.0,132.8,132.8,NaN,NaN,NaN,70.5,916.7,0.0,121800.0,121800.0,racks_13

In [18]:
df_all.to_csv('preprocessing_data_A.csv', index=None)